name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Instalamos nuestro paquete y extras de desarrollo
          pip install -e .[dev]

      - name: Lint with Black
        run: |
          black --check .

      - name: Lint with isort
        run: |
          isort --check-only .

      - name: Lint with Flake8
        run: |
          # Flake8 leerá la configuración desde los ficheros del proyecto (.flake8, pyproject.toml)
          flake8 .

      - name: Type check with mypy
        run: |
          mypy .

      - name: Run tests with coverage
        run: |
          pytest -q --cov=.

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}