name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Instalamos nuestro paquete y extras de desarrollo
          pip install -e .[dev]

      - name: Lint with Black
        run: |
          black --check .

      - name: Lint with Flake8
        run: |
          flake8

      - name: Run tests
        run: |
          pytest -q