name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:                           # ← 2 espacios antes de 'test'
    runs-on: ubuntu-latest        # ← 4 espacios antes de 'runs-on'
    strategy:                     # ← 4 espacios antes de 'strategy'
      matrix:
        python-version: [3.8, 3.9, 3.10, 3.11]

    steps:                        # ← 4 espacios antes de 'steps'
      - name: Checkout code       # ← 6 espacios antes de '- name'
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black flake8
          pip install -e .[dev]

      - name: Lint with Black
        run: black --check .

      - name: Lint with Flake8
        run: flake8

      - name: Run tests
        run: pytest -q
